version: "2"
services:
  client:
    container_name: client
    build: ./client
    ports:
      - "3000:3000"
    links:
      - server
    volumes:
      - ./client/src:/client/src

  server:
    container_name: server
    build: ./server
    environment:
      PORT: 4000
      NODE_ENV: development
      MONGODB_URI: "mongodb://mongo:27017/kalicos"
      JWT_SECRET: "jd5n6pfl2kdfnkl395jasdfn"
      API_KEY_GMAPS: "<GMAPS_KEY_HERE>"
    ports:
      - "4000:4000"
    command: nodemon src/server.js 
    links:
      - mongo
    volumes:
      - ./server/src:/server/src

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
